### ISSUE TITLE
JS-Error: Das Objekt unterstützt die Eigenschft oder Methode "getTime" nicht

### ISSUE THREAD

**Issue by kloana** [berwinter/uvr1611#14]
Hallo,

erstmal, vielen Dank für deine SW!  Auslesen und einpflegen der Daten funktioniert super! 

Leider habe ich beim JS ein Problem. Der Graph wird nicht angezeigt und obige Fehlermeldung kommt im IE11.

Vielleicht weißt du ja eine Lösung zu diesem Problem.
Danke,
lg
Herby (von der anderen Seite vom Alpl)

**Comment by berwinter** [comment]
Hallo Herby,

Vermutlich kommt der IE11 mit dem Datums-Format nicht klar und kann dann .getTime() nich auf dem Objekt (null) ausführen. Werde ich mir ansehen und wenn möglich fixen.

LG Bertram

**Comment by berwinter** [comment]
fixed in v210
