### ISSUE TITLE
Also possible to get data from CMI-Webinterface

### ISSUE THREAD

**Issue by creithm** [berwinter/uvr1611#15]
Hi,

great project! Is it also possible to load the data from the CMI Webinterface like in WinSol? 
How is an example setup for URL, username and password?

I use there this URL:
https://cmi.ta.co.at/webi/CMI007686/index.cgi

best regards
Christoph

**Comment by s--o--n--y** [comment]
Hi! 
Thx :-) I'll check that by time. If you already found a solution pls forward.

cheers sony

**Comment by creithm** [comment]
I didn't found any solution up to now. It would be great if you can check it and provide a solution !
Christoph

**Comment by berwinter** [comment]
Currently this is not possible. I am not sure if it is the same interface like accessing directly the CMI. First thing would be do try if the connection can be logged Wireshark (seems to be an encrypted HTTPS connection). This should show which information is transmitted by WinSOL to the TA server and would allow to implement the same interface in the Datalogger. Unfortunately I do not have a CMI and TA account, so I need to relay on your help for implementing this.

**Comment by creithm** [comment]
This are the URL's (CMI000100 is your serial number)
https://cmi.ta.co.at/webi/CMI000100/LOG/2016/data_2016_06_06_10_36_22.log
http://cmi-spj/LOG/2016/data_2016_06_06_10_36_22.log

**Comment by berwinter** [comment]
I implemented the communication with the web portal in the latest release (v2.12). Please use the following configuration:

```
[mysql]
server = localhost
user = uvr1611
password = uvr1611
database = uvr1611

[uvr1611]
logger = "portal"
blnet_login = false
address = 10.0.0.100
port = 40000
reset = false
http_port = 80
user = testuser
password = 1234
cmi = CMIxxxxxxx

[app]
name = "Solar/Heizung Datenauswertung"
debug = false
email = bertram.winter@gmail.com
chartcache = 600
latestcache = 60
reduction = 2
```
