### ISSUE TITLE
https bug - openweathermap.org

### ISSUE THREAD

**Issue by nils50122** [berwinter/uvr1611#17]
when i set the my domain with the dataloggerpro to https, the weather screen is blank.
I find no files with the http-link to openweathermap.

Can you set the link to openweathermap to https?

![weather](https://cloud.githubusercontent.com/assets/24404295/20914715/c659c69e-bb81-11e6-8412-13dddd1f952c.JPG)

**Comment by berwinter** [comment]
Hi

unfortunately SSL is not included in the free subscription. Please see http://www.openweathermap.org/price, at least the developer account would be needed.

**Comment by nils50122** [comment]
increase the max_execution_time to 120 and solve the problem, big thanks :)
