### ISSUE TITLE
first access to an chart - slowly loading with an error

### ISSUE THREAD

**Issue by nils50122** [berwinter/uvr1611#18]
when i click on a schema with a normal chart, i see the loading circle and after a time there comes an error.

When i reload the page (f5 in browser) the chart is there without an error.

Is that a cache problem?

**Comment by berwinter** [comment]
The default timeout for PHP is 60 seconds. Please increase this limit in your php.ini if it is not sufficient  to load all data.

**Comment by nils50122** [comment]
increase the max_execution_time to 120 and solve the problem, big thanks :)
