### ISSUE TITLE
Automatic Database clean function

### ISSUE THREAD

**Issue by svenp** [berwinter/uvr1611#31]
Hi,
is there a function where i can set the maximum time in Database t_data.
today -365 then all data older then 365days will be deleted automatic in mysql database.
Or can i set a cronjob ervery month witch will delete data older then xxx days, years ....

Regards
Sven

**Comment by berwinter** [comment]
Hi,

yes, you can do this using SQL. (I would recommend it only for t_data - the other historic tables (energies, max, min) store just one value per day and do not get that big).

`DELETE FROM t_data WHERE date < DATE_SUB(NOW(), INTERVAL 1 YEAR);`

Please verify first if the correct datasets are selected by:

`SELECT FROM t_data WHERE date < DATE_SUB(NOW(), INTERVAL 1 YEAR);`

Regards,
Bertram

**Comment by svenp** [comment]
Now i have a cron script 

`#!/bin/bash`
`#For testing`
`#mysql -u  uvr1611 -ppassword -D uvr1611 --execute="SELECT * FROM t_data WHERE date < DATE_SUB(NOW(), INTERVAL 2 YEAR)"`

`#Now delete`
`mysql -u  uvr1611 -ppassword -D uvr1611 --execute="DELETE * FROM t_data WHERE date < DATE_SUB(NOW(), INTERVAL 2 YEAR)"`


-u [user] -p [password] -D [Database]
Thank you for your help
